from __future__ import annotations

import random
from dataclasses import dataclass, field
from enum import Enum
from typing import Protocol


class TrustedLatex:
    """LaTeX string that is safe for compilation.

    This is a trust boundary marker. Only the math engine should create
    TrustedLatex instances — they represent LaTeX generated by SymPy and
    our templates, NOT user input.

    The PDF service checks for this type before compiling. Raw strings
    cannot be passed to the LaTeX compiler without going through this wrapper.
    """

    __slots__ = ("_value",)

    def __init__(self, value: str) -> None:
        self._value = value

    @property
    def value(self) -> str:
        return self._value

    def __str__(self) -> str:
        return self._value

    def __repr__(self) -> str:
        return f"TrustedLatex({self._value!r})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TrustedLatex):
            return self._value == other._value
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._value)

    def __bool__(self) -> bool:
        return bool(self._value)


class Difficulty(str, Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


ALL_DIFFICULTIES = list(Difficulty)


class Topic(str, Enum):
    ALGEBRA = "algebra"
    FUNCTIONS = "functions"
    GEOMETRY = "geometry"
    TRIGONOMETRY = "trigonometry"
    CALCULUS = "calculus"
    COMBINATORICS = "combinatorics"


@dataclass(frozen=True)
class GeneratedProblem:
    question_latex: TrustedLatex
    answer_latex: TrustedLatex
    topic: Topic
    difficulty: Difficulty
    subtopic: str = ""
    metadata: dict = field(default_factory=dict)
    solution_steps: tuple[TrustedLatex, ...] = ()

    def __post_init__(self):
        if not isinstance(self.question_latex, TrustedLatex):
            raise TypeError(
                f"question_latex must be TrustedLatex, got {type(self.question_latex).__name__}. "
                "Wrap with TrustedLatex() inside engine templates only."
            )
        if not isinstance(self.answer_latex, TrustedLatex):
            raise TypeError(
                f"answer_latex must be TrustedLatex, got {type(self.answer_latex).__name__}. "
                "Wrap with TrustedLatex() inside engine templates only."
            )


class ProblemTemplate(Protocol):
    topic: Topic
    subtopic: str
    supported_difficulties: list[Difficulty]

    def generate(self, difficulty: Difficulty, rng: random.Random) -> GeneratedProblem: ...


@dataclass
class GenerationConfig:
    topics: list[Topic]
    difficulty: Difficulty
    count: int
    seed: int | None = None
    subtopics: dict[Topic, list[str]] | None = None  # None = all subtopics

    def __post_init__(self):
        if not 1 <= self.count <= 50:
            raise ValueError(f"Question count must be 1-50, got {self.count}")
        if not self.topics:
            raise ValueError("At least one topic is required")


class GenerationError(Exception):
    pass
